### ISSUE TITLE
yarn boot 安装报错 yarn run build exited 2 in '@foxpage/foxpage-plugin-unpkg'

### ISSUE THREAD

**Issue by lphkxd** [foxpage/foxpage#12]
![image](https://user-images.githubusercontent.com/16346895/183232279-0c510ca6-782b-41f7-9469-9263c7f312b3.png)

![image](https://user-images.githubusercontent.com/16346895/183232261-f6d8bd5d-326f-47ab-96ab-5e26fb059b32.png)

**Comment by drxiao1** [comment]
@lphkxd 你好，该问题已处理，有空可以再尝试下。感谢。
