### ISSUE TITLE
文档不对

### ISSUE THREAD

**Issue by 359587** [foxpage/foxpage#2]
$ yarn boot

$ npm run start-server:prod

// 初始化数据
$ npm run init-server:prod
没有一个可以执行的,npm run start 可以执行

**Comment by yhdeng** [comment]
麻烦问下，你本地有安装yarn吗？ 你是在项目的根目录运行的命令吗？方便提供下报错的信息吗？

**Comment by HanAsteroid** [comment]
<img width="830" alt="image" src="https://user-images.githubusercontent.com/13330492/156506040-5d5e1bdd-1adb-4bed-a61a-d81ecca44d43.png">
同样的问题，没有文档上写的那几个命令

**Comment by drxiao1** [comment]
@359587 @HanAsteroid ，感谢反馈。
启动子项目需要先进入到对应子项目下进行操作，[详情](https://github.com/foxpage/foxpage-documentation/blob/main/docs/developer/start/install.md)。文档已更新好
![image](https://user-images.githubusercontent.com/22312959/156518648-b9c0a27b-c27b-4330-8ba7-5ea71c405680.png)
