### ISSUE TITLE
代码运行问题

### ISSUE THREAD

**Issue by wanshikaimo** [foxpage/foxpage#3]
![image](https://user-images.githubusercontent.com/42828171/156530146-b2f3592b-9b24-4258-bcd5-55bcbc42e248.png)
按照官网的用户手册注册静态资源
![image](https://user-images.githubusercontent.com/42828171/156530255-89fd8c4e-d021-406f-8351-98d8790122d5.png)
不能通过是什么原因呢

**Comment by wanshikaimo** [comment]
![image](https://user-images.githubusercontent.com/42828171/156530788-cd400ddc-6afd-486b-9c60-85d3296577a9.png)
![image](https://user-images.githubusercontent.com/42828171/156531196-152999a1-64c8-497a-a012-6c902b5bf516.png)

这里的代码是不是有点问题，无论是中文环境还是英文环境下values并没有filepath属性，解构赋值没有意义。
在使用平台时卡在了注册静态资源这边，望大佬帮忙解决

**Comment by yhdeng** [comment]
问题已修复发布，请再拉下最新的代码试下。
