### ISSUE TITLE
如何引入静态资源

### ISSUE THREAD

**Issue by wanshikaimo** [foxpage/foxpage#4]
![image](https://user-images.githubusercontent.com/42828171/156686333-09ed5a7e-2ca0-4d90-9d08-ec6e575cae65.png)
官网上的tian添加静态资源的描述不是太懂，比如我想要引入@fox-design/antd-button资源，filepath应该填什么呢

**Comment by wanshikaimo** [comment]
![image](https://user-images.githubusercontent.com/42828171/156686756-431bfa9c-85f0-480f-ae92-b2887ef0d297.png)
![image](https://user-images.githubusercontent.com/42828171/156686815-42fbdfd1-bbe5-4dcb-911b-4f49cebd0dea.png)
这是应用相关的配置

**Comment by yhdeng** [comment]
@wanshikaimo 手动新增资源包时，需要在资源目录的指定资源组下增加资源包，如果不存在资源组，需要先手动创建一个。如下是创建资源包的步骤：
1，创建包文件夹，如：“@fox-design/antd-button”，如下图1
![图1](https://user-images.githubusercontent.com/6350107/156706457-35deb39d-76c1-44b4-a208-758838da6b33.png)
2，进入包文件夹，创建包版本号，如"0.1.0", 该版本号需要真实存在的。
![图2](https://user-images.githubusercontent.com/6350107/156706640-e9277ed9-f5a3-4cdc-81c8-bc71d39ab864.png)
3，进入版本号文件夹，创建包的详情文件目录，这个目录是基于具体的包信息的，以@fox-design/antd-button包为例，该版本下有cjs和cmd两个文件夹，因此需要先创建这个两个文件夹，然后再进入umd文件夹下，创建具体的文件，直接将再unpkg的文件地址复制进去就行了。如下图:
![图三](https://user-images.githubusercontent.com/6350107/156707078-c225c761-6902-4a9e-98ea-4d12839ed87f.png)

其他的文件都按照以上步骤来创建。

如还有问题，请及时反馈。

**Comment by wanshikaimo** [comment]
![image](https://user-images.githubusercontent.com/42828171/156713373-ec12bf84-88de-4b08-9164-44c3f8990dd0.png)
如果我在新建文件夹的时候，如上图直接添加两级目录
再点进创建好的目录如下图，新增文件夹和新增文件就会被disable
![image](https://user-images.githubusercontent.com/42828171/156713554-7cbf5f55-764d-48b0-9d9a-c6991be5f999.png)

**Comment by yhdeng** [comment]
@wanshikaimo 这个事逻辑处理问题，已经修复发上去了，麻烦再更新下代码。

**Comment by wanshikaimo** [comment]
可以加一下微信吗，感觉还是有些问题




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "foxpage/foxpage"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年3月4日(星期五) 下午3:10
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [foxpage/foxpage] 如何引入静态资源 (Issue #4)





 
@wanshikaimo 这个事逻辑处理问题，已经修复发上去了，麻烦再更新下代码。
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by wanshikaimo** [comment]
方便加一下wechat吗，改了正则以后好像还有别的问题。这里交流不太方便

**Comment by yhdeng** [comment]
@wanshikaimo 我们创建了一个微信群，有需要的话，可以加入进来。

![微信群](https://user-images.githubusercontent.com/6350107/156721229-71b9ce36-6333-4b38-823d-8e4c7541d165.png)

**Comment by HanAsteroid** [comment]
> @wanshikaimo 我们创建了一个微信群，有需要的话，可以加入进来。
> 
> ![微信群](https://user-images.githubusercontent.com/6350107/156721229-71b9ce36-6333-4b38-823d-8e4c7541d165.png)

二维码过期了
