### ISSUE TITLE
请教下DSL的问题

### ISSUE THREAD

**Issue by wanghao137** [foxpage/foxpage#5]
可视化页面搭建完成后，可以生成DSL代码，请问下DSL代码在后续如果使用以及如何引用到其他项目中，谢谢。另:麻烦加下技术支持微信群，谢谢。

**Comment by WangYiLong** [comment]
不太清楚你真是意图，DSL这一层用户可以不用太去关注，如果想要分享DSL到其他项目，可以使用我们提供的商店功能进行跨项目DSL复制，技术群
![image](https://user-images.githubusercontent.com/4746568/160554584-7cf990ff-a3a4-4133-b8f6-0ba0c85a6752.png)
