### ISSUE TITLE
本地安装: 步骤 3：配置 foxpage app server 无法运行

### ISSUE THREAD

**Issue by soonboylena** [foxpage/foxpage#7]
按照文档中“本地安装”步骤中： “步骤 3：配置 foxpage app server ”
执行以下命令后，
```
 cd foxpage/foxpage-app-server
 npm install
 npm run start
```
出现错误，显示无法找到 manifest.json文件。

`init static server proxy failed:/home/sunbo/Workspace/foxpage/hellofoxpage/foxpage-app-server/library/manifest.json: ENOENT: no such file or directory, open '/home/sunbo/Workspace/foxpage/hellofoxpage/foxpage-app-server/library/manifest.json'`

![image](https://user-images.githubusercontent.com/16619932/166182973-2ae7c65a-1972-4a3e-abab-d1db1eb44cb7.png)

**Comment by drxiao1** [comment]
不好意思，文档还未更新。
需要在run start之前执行下run build命令，打包编译出依赖的静态资源放在项目根目录library中，启动时依赖

**Comment by soonboylena** [comment]
执行 npm install 后，执行 npm run build,仍然发生异常

![image](https://user-images.githubusercontent.com/16619932/167070241-4f433060-2a84-4622-8578-0602d12b137f.png)


能否指导一下，我应该怎么处理？
